### PR TITLE
Feature/pr template

### PR DESCRIPTION
**Pull request by st3v3nhunt**
The guidance/instructions are now comments. This means if they are not deleted they are not visible in the rendered view of the issue.

### CODE REVIEW

**Review by ajthomascouk — COMMENTED** [review]
Is there anywhere where we tell people that they need to add their new style and elements to the style guide?

**Comment by st3v3nhunt** [comment]
This? https://github.com/nhsuk/frontend-library/pull/18/files#diff-195a635ad245ded9076330e31134bd80R30

**Comment by ajthomascouk** [comment]
How did it miss that!?

**Review by ajthomascouk — APPROVED** [review]
LGTM

**Pull request merged**
